### ISSUE TITLE
Adding navigateFallback does not work

### ISSUE THREAD

**Issue by PSPanesar** [Aerolab/nextjs-pwa#4]
Hi,

Thank you for providing an example implementation of a PWA with nextjs. I was implementing a similar model to my nextjs app and with my config for the service worker in next.config.js i added then setting called navigateFallback="/index" to add a fallback page if the network is down so the service worker can deliver that and the app continues to display some cached content even if the network is down. 

That setting however doesn't work and when the network is turned off it still shows a 404 page saying the page can not be found and so the redirect doesn't work. 

I wonder if you have found this bug or have a solution to get that to work?

BW
P

**Comment by RobertoGonzalez** [comment]
Sadly this is a known issue with both sw-precache and next-offline and the only solution consists of wrapping requests in a local cache and then defining an app shell to get everything to work. It's not particularly easy to do, so it's better to just use next-offline to at least get some offline support.
