### ISSUE TITLE
using styled-components

### ISSUE THREAD

**Issue by lonelydatum** [Aerolab/nextjs-pwa#5]
I see you are using <style jsx>. Can you please show me how to use styled-components instead?

I know how to use it when it extends Document since it has access to the renderPage. But with the Layout.js it is not extending Document so how would you get access to the renderPage?

Thanks

**Comment by RobertoGonzalez** [comment]
The official example that [extends _document.js](https://github.com/zeit/next.js/tree/canary/examples/with-styled-components) is pretty much all you have to do. In the repo, Layout is just another React component and shouldn't cause any issues with this. It's mostly a decision on how to structure the code.
