### ISSUE TITLE
Where to find the documentation for the webpack plugin options for runtimeCaching and verbose?

### ISSUE THREAD

**Issue by johhansantana** [Aerolab/nextjs-pwa#6]
I've visited https://github.com/goldhand/sw-precache-webpack-plugin but there's no documentation on the options you added in the `nextjs.config.js` on the `verbose` and `runtimeCaching`

Could you point me to the documentation for these and what they do?

**Comment by RobertoGonzalez** [comment]
The plugin is a wrapper around sw-precache, so most of the options are the same. You can find the docs here: https://github.com/GoogleChromeLabs/sw-precache .
